FROM rockylinux:9

VOLUME /host

RUN dnf -y group install "Development Tools"
RUN dnf -y install rpm-build epel-release
#RUN dnf config-manager --set-enabled crb
RUN dnf -y install slurm slurm-libs slurm-devel
